version: "3.9"

services:
    php-apache:
        ports:
            - "80:80"
        build: './build/php'
        volumes:
            - ./app:/var/www/html
    mysql:
        ports:
            - "3306:3306"
        build: './build/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: "1234"
            MYSQL_DATABASE: "Vcorp"
        volumes:
            - ./dbData:/var/lib/mysql
    myadmin:
        ports:
            - "5000:80"
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:db
volumes:
    app: 
    dbData: